### ISSUE TITLE
Array of arbitrary type

### ISSUE THREAD

**Issue by nomisRev** [nomisRev/OpenAPI-kt#62]
An array of arbitrary types can be defined as:

```yaml
type: array
items: {}
# [ "hello", -2, true, [5.7], {"id": 5} ]
```

This should result in a `List<JsonElement>` which is the only accurate result here.
