### ISSUE TITLE
Properly implement AnyValue (empty Schema)

### ISSUE THREAD

**Issue by nomisRev** [nomisRev/OpenAPI-kt#65]
# Any Type

A schema without a type matches any data type – numbers, strings, objects, and so on. {} is shorthand syntax for an arbitrary-type schema:

```yaml
components:
  schemas:
    AnyValue: {}
```

If you want to provide a description:

```yaml
components:
  schemas:
    AnyValue:
      description: Can be any value - string, number, boolean, array or object.
```

The above is equivalent to:

```yaml
components:
  schemas:
    AnyValue:
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
```

If the null value needs to be allowed, add nullable: true:

```yaml
components:
  schemas:
    AnyValue:
      nullable: true
      description: Can be any value, including `null`.
```
